pipelines:
  default:
    # - step:
    #     name: Build and Test
    #     image: python:3.9
    #     caches:
    #       - pip
    #     script:
    #       - pip install -r requirements.txt  # Install Python dependencies
          
    - step:
        name: OWASP ZAP Scan
        services:
          - docker
        script:
          - docker pull owasp/zap2docker-stable  # Pull the OWASP ZAP Docker image
          - docker run -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:8080 -r zap_report.html  # Run OWASP ZAP scan
        artifacts:
          - zap_report.html  # Save the ZAP report as an artifact

definitions:
  services:
    docker:
      memory: 1024 
