# This is a basic workflow to help you get started with Actions

name: CI Pipeline, ZAP Scan

on: 
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Install Dependencies
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

  zap_scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Sanity check of git actions
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo No error. Do the necessary build steps here.
  scans:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: ZAP API Scan

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log current directory
        run: echo ${pwd}
      - name: Pull ZAP OWASP Image
        run: docker pull owasp/zap2docker-weekly
      - name: Run ZAP API Scan
        run: |
          sudo docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-api-scan.py -t openapi.json -f openapi -c api-scan.conf
        # run: sudo docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-api-scan.py -t dev-wiki-api.json -f openapi -r test_report_$(date -u +'%Y%m%d').html
